### PR TITLE
#162948987 API documentation with swagger

### PR DESCRIPTION
**Pull request by eduhmik**
#### What does this PR do?
It seeks to document our API using swagger

#### Description of the task to be completed?
-install django-rest-swagger==2.1.0
-configure swagger in settings.py
-run locally in the browser

#### How should this be manually tested?
git clone the [repo](https://github.com/andela/ah-fulldeck.git)
cd into it and install requirements using `pip install -r requirements.txt`
run the server using `python manage.py runserver`
open the localhost url in the browser

screenshot 2019-01-11 at 15 43 48
screenshot 2019-01-11 at 15 44 03

#### Relevant PT stories
[#162948987](https://www.pivotaltracker.com/story/show/162948987)

### CODE REVIEW

**Review by Nyakaru — COMMENTED** [review]
Good work so far. But what maybe you could consider looking up into coveralls. Its build is failing.

**Comment by eduhmik** [comment]
@Nyakaru The builds are failing only because the coveralls have decreased with the introduction of new code.

**Comment by kzyangiro** [comment]
@eduhmik 
1. /api/v1 is always the base route to the api which should directly lead to the api's first endpoint - Mostly homeroute. I would therefore need you to adjust the documentation to point to /api/v1/docs

**Comment by charitymarani** [comment]
I think you have done great, though the coveralls check is still failing because of decreased coverage but the work is fine

**Review by kzyangiro — APPROVED** [review]

**Pull request merged**
