### PR TITLE
#163086301 Setup flake8

### PR DESCRIPTION
**Pull request by Nicanor008**
#### What does this PR do?
Sets up flake8

#### Description of Task to be completed?
Sets up flake8 in requirements.txt

#### How should this be manually tested?
After cloning this repo, open the terminal and run `flake 8 usr/path/file` to test a directory or `flake8 usr/path/file.py` to test a single file against pep8 style guide

screen shot 2019-01-10 at 16 44 23

#### What are the relevant pivotal tracker stories?
[#163086301](https://www.pivotaltracker.com/story/show/163086301)

### CODE REVIEW

**Comment by Nyakaru** [comment]
Good work so far. Check the Travis CI build fails and fix them.

**Comment by eduhmik** [comment]
Nice work! What are the errors that Travis is throwing?

**Comment by Nicanor008** [comment]
@eduhmik the build is now OK, the error was due to lack of coveralls and coverage report in the .travis.yml file

**Review by Hesbon5600 — COMMENTED** [review]
Looks good after fixing the build

**Review by charitymarani — APPROVED** [review]

**Comment by JoshuaKodhe** [comment]
I like that you worked on and fixed the errors that TravisCI was throwing. 
Keep up the good work. 

The screenshot in your PR, however, shows that there are formatting errors in the document. 
Please look into them.

**Comment by Nicanor008** [comment]
@JoshuaKodhe, the screenshot shows how you run the flake8, if you run the same command without any error then you will get no feedback. I just used it to show it is setup into this project

**Comment by Nicanor008** [comment]
I have moved the screenshot to "how to manually test manually" because it indicates the results after testing this PR manually, as advised by @JoshuaKodhe

**Comment by kzyangiro** [comment]
@Nicanor008 Resolve the merge conflicts then ensure to fix the flake8 errors first. A few imports of code lines that you may have leave irrespective of the error, find a flake8 ignore command for the lines. I would like to merge the PR when flake8 flags no error so that next tasks will just handle .

**Review by kzyangiro — APPROVED** [review]

**Pull request merged**
