### PR TITLE
#162948984 Configure Authors Haven to use PostgreSQL as DB Engine

### PR DESCRIPTION
**Pull request by Nyakaru**
#### What does this PR do?
Configure Authors Haven to use PostgreSQL as DB Engine
#### Description of Task to be completed?
- install postgres
- configure postgres in app settings
#### What are the relevant pivotal tracker stories?
[#162948984](https://www.pivotaltracker.com/story/show/162948984)

### CODE REVIEW

**Comment by charitymarani** [comment]
@Nyakaru great work but you could name the PR better. Please refer to the PR naming conventions in the engineering playbook

**Comment by Nyakaru** [comment]
> @Nyakaru great work but you could name the PR better. Please refer to the PR naming conventions in the engineering playbook

Noted. Thanks for the reminder

**Comment by Nicanor008** [comment]
Instead of providing the whole link to the PT story it should be the story ID with link. Consider this [#storyid](pt story link)

**Comment by Nyakaru** [comment]
> Instead of providing the whole link to the PT story it should be the story ID with link. Consider this [#storyid](pt story link)

Noted. Thanks for the reminder.

**Pull request merged**
